### ISSUE TITLE
Automation: skip not supported tests

### ISSUE THREAD

**Issue by apetrovskiy** [neonevm/neon-compatibility#113]
We need to skip tests touching eth_getStorageAt, evm_setAutomine:

1. ERC20Votes, ERC20VotesComp
http://159.69.223.194/#categories/bc4f1bc443a7ed6162395ea17da3e0c6/b462eb4fb8a3f29c/
http://159.69.223.194/#categories/bc4f1bc443a7ed6162395ea17da3e0c6/82dc2273f73317ca/
2. BeaconProxy TransparentUpgradeableProxy
http://159.69.223.194/#categories/46cf8e2332574f1d447bda346abdaf95/9e6b112af49924d2/
http://159.69.223.194/#categories/46cf8e2332574f1d447bda346abdaf95/f59c2a7788c5b3eb/
3. Contract: GovernorTimelockCompound deplicated underlying call.run
`Target block #(16859) is lower than current block #(16879)`
`Error: Target block #(16859) is lower than current block #(16879)`
`                    at Object.advanceBlockTo (node_modules/@openzeppelin/test-helpers/src/time.js:22:38)`
`                    at runMicrotasks (<anonymous>)`
`                    at processTicksAndRejections (node:internal/process/task_queues:96:5)`
`                    at Context.<anonymous> (test/governance/GovernorWorkflow.behavior.js:61:9)`
                    
Please notify @vodolaz after the merge

**Comment by gigimon** [comment]
https://github.com/neonlabsorg/openzeppelin-contracts/pull/2/files

**Comment by gigimon** [comment]
@apetrovskiy when you complete CR i will write a comment to issue for uncomment some tests and create ticket for this. And change link to submodule in neon-compatibility repo
